[package]
name = "qsv"
version = "0.1.0"
edition = "2021"
description = "A tool for elastic and rapid filtering of huge CSV files"
authors = ["sumeshi <sum3sh1@protonmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
polars = { version = "0.33", features = ["lazy", "csv", "temporal", "strings"] }
regex = "1.9"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.8"
serde_yaml = "0.9"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
comfy-table = "7.1"
glob = "0.3"
encoding_rs = "0.8.32"